### ISSUE TITLE
MaskableFrameLayout.dispatchDraw java.lang.RuntimeException:

### ISSUE THREAD

**Issue by smith121321** [christophesmet/android_maskable_layout#36] opened 2018-12-31 06:33 UTC
Report 1 of 4
java.lang.RuntimeException

com.christophesmet.android.views.maskableframelayout.MaskableFrameLayout.dispatchDraw
java.lang.RuntimeException: 
  at android.graphics.BaseCanvas.throwIfCannotDraw (BaseCanvas.java:55)
  at android.graphics.BaseCanvas.drawBitmap (BaseCanvas.java:120)
  at android.graphics.Canvas.drawBitmap (Canvas.java:1434)
  at android.graphics.drawable.BitmapDrawable.draw (BitmapDrawable.java:529)
  at android.widget.ImageView.onDraw (ImageView.java:1370)
  at android.view.View.draw (View.java:19328)
  at android.view.View.draw (View.java:19192)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at com.christophesmet.android.views.maskableframelayout.MaskableFrameLayout.dispatchDraw (MaskableFrameLayout.java:204)
  at android.view.View.buildDrawingCacheImpl (View.java:18549)
  at android.view.View.buildDrawingCache (View.java:18415)
  at android.view.View.draw (View.java:19037)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.updateDisplayListIfDirty (View.java:18243)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.updateDisplayListIfDirty (View.java:18243)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.updateDisplayListIfDirty (View.java:18243)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.draw (View.java:19331)
  at android.view.View.updateDisplayListIfDirty (View.java:18257)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.updateDisplayListIfDirty (View.java:18243)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.updateDisplayListIfDirty (View.java:18243)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.updateDisplayListIfDirty (View.java:18243)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.draw (View.java:19331)
  at android.view.View.updateDisplayListIfDirty (View.java:18257)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at com.xiaopo.flying.sticker.StickerView.dispatchDraw (StickerView.java:199)
  at android.view.View.draw (View.java:19331)
  at android.view.View.updateDisplayListIfDirty (View.java:18257)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.updateDisplayListIfDirty (View.java:18243)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.updateDisplayListIfDirty (View.java:18243)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.updateDisplayListIfDirty (View.java:18243)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.updateDisplayListIfDirty (View.java:18243)
  at android.view.View.draw (View.java:19045)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4401)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4180)
  at android.view.View.draw (View.java:19331)
  at com.android.internal.policy.DecorView.draw (DecorView.java:974)
  at android.view.View.updateDisplayListIfDirty (View.java:18257)
  at android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:676)
  at android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:682)
  at android.view.ThreadedRenderer.draw (ThreadedRenderer.java:790)
  at android.view.ViewRootImpl.draw (ViewRootImpl.java:3091)
  at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:2884)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2437)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1446)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6954)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:925)
  at android.view.Choreographer.doCallbacks (Choreographer.java:737)
  at android.view.Choreographer.doFrame (Choreographer.java:669)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:911)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:192)
  at android.app.ActivityThread.main (ActivityThread.java:6671)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:826)

**Comment by smith121321** [comment] 2018-12-31 06:34
Please try to resolve this issue, I updated dependency but still this issue is not resolved.

**Comment by christophesmet** [comment] 2019-01-22 10:04
I think this is caused by drawing a too large bitmap.
Can you provide some more detailed information about the mask you are using ?

**Comment by christophesmet** [comment] 2019-06-17 08:18
Closing after no updates.

**Closed by christophesmet** 2019-06-17 08:18 UTC
